# Generated by Django 5.1.6 on 2025-03-01 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('day', '0003_cate'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cate',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='day.cate'),
            preserve_default=False,
        ),
    ]
